name: Build and Deploy

on:
  # Run this pipeline for all pushes into main
  push:
    branches:
      - main

jobs:
  build:
    # Job name
    name: Build and Deploy
    
    # Run on ubuntu
    runs-on: ubuntu-latest

    steps:

      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Node
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Build
      - name: Build
        run: npm run build

      # Deploy to remote server
      - name: Deploy to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          rm: true
          source: "build/"
          target: "${{ secrets.REMOTE_DIR }}"